### ISSUE TITLE
New v7.0 Manifest Not Syncing

### ISSUE THREAD

**Issue by PizzaG** [AfterlifeOS/android_manifest#1]
repo init -u https://github.com/AfterlifeOS/android_manifest.git -b V7.0 --git-lfs --no-clone-bundle

manifests:
fatal: couldn't find remote ref refs/heads/V7.0
manifests: sleeping 4.0 seconds before retrying
fatal: cannot obtain manifest https://github.com/AfterlifeOS/android_manifest.git
================================================================================
Repo command failed: UpdateManifestError
	Unable to sync manifest default.xml

**Comment by aepranata** [comment]
Manifest was updated Just try

**Comment by HinohArata** [comment]
@aepranata @ini udah sp sept pak? @aepranata

**Comment by PizzaG** [comment]
ahh, I see you changed the repo init command, working now, thanks much!!
